Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-07, with the labels that each got.

#409 Added disk space requirements
  downstream/modules/platform/ref-system-requirements.adoc
Labels: backport to 2.1, Backport to 2.2, Ready for peer review

#374 Delete CODEOWNERS file
  CODEOWNERS
Labels: Ready for peer review

#412 AAP-1439: Add section for Access Control Requirements
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/modules/platform/ref-access-control-requirements.adoc
Labels: 2.2, Backport to 2.2

#421 Updated title and inventory file
  downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
Labels: Ready for peer review

#424 Fix password example in codeblock
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
Labels: backport to 2.1, Backport to 2.2, Ready for peer review

#426 Fix password example in codeblock (#424)
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
Labels: 2.2

#427 Removed instructions for installing builder with pip
  downstream/assemblies/builder/assembly-building-off-existing-ee.adoc
  downstream/modules/builder/con-pip-based-req.adoc
  downstream/modules/builder/proc-installing-builder.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2, Ready for peer review

#415 AAP-4359 Maintain Hub API during AAP upgrade + basic upgrade section
  downstream/assemblies/platform/assembly-aap-upgrades.adoc
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/assemblies/platform/assembly-migrate-isolated-execution-nodes.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrades-legacy.adoc
  downstream/modules/platform/con-aap-upgrades.adoc
  downstream/modules/platform/con-upgrade-planning.adoc
  downstream/modules/platform/ini/clustered-nodes.ini
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
  downstream/modules/platform/proc-upgrade-installer.adoc
  downstream/titles/upgrade/master.adoc
Labels: 2.2, Ready for peer review

#432 [Backport 2.2] AAP-4359 Maintain Hub API during AAP upgrade + basic upgrade section …
  downstream/assemblies/platform/assembly-aap-upgrades.adoc
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/assemblies/platform/assembly-migrate-isolated-execution-nodes.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrades-legacy.adoc
  downstream/modules/platform/con-aap-upgrades.adoc
  downstream/modules/platform/con-upgrade-planning.adoc
  downstream/modules/platform/ini/clustered-nodes.ini
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
  downstream/modules/platform/proc-upgrade-installer.adoc
  downstream/titles/upgrade/master.adoc
Labels: 2.2, Ready for peer review

#431 AAP-4775 Add user-replaced value for SSH tunnelling IP address
  downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-ssh-tunnel.adoc
Labels: 2.1, Needs backport to 2.1, Ansible on Clouds, Ansible on Azure, Needs backport to 2.2

#434 2.1 AAP-4775 Add user-replaced value for SSH tunnelling IP address (#431)
  downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-ssh-tunnel.adoc
Labels: 2.1, Ansible on Clouds, Ansible on Azure

#433 2.2 AAP-4775 Add user-replaced value for SSH tunnelling IP address (#431)
  downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-ssh-tunnel.adoc
Labels: 2.2, Ansible on Clouds, Ansible on Azure

#352 AAP-1972: Add subsection on active offline token
  downstream/modules/automation-hub/con-offline-token-active.adoc
  downstream/titles/hub/getting-started/master.adoc
Labels: 2.1, Needs backport to 2.1, Peer review complete

#436 2.1 AAP-1972: Add subsection on active offline token (#352)
  downstream/modules/automation-hub/con-offline-token-active.adoc
  downstream/titles/hub/getting-started/master.adoc
Labels: 2.1, Backported to 2.1

#414 Added allowlisted domains
  downstream/modules/automation-hub/proc-create-synclist.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2
