Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-03, with the labels that each got.

#272 aap-2389 Add delete user module to controller
  downstream/modules/automation-hub/proc-delete-user.adoc
  downstream/modules/controller/proc-controller-delete-user.adoc
Labels: 2.1, backport to 2.1

#283 Fix operator modules
  downstream/modules/platform/con-operator-additional-resources.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
Labels: bug, backport to 2.1

#285 AAP-2853 Update Providing feedback info
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-on-azure/docinfo.xml
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/analytics/automation-savings-planner/docinfo.xml
  downstream/titles/analytics/reports/docinfo.xml
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/builder/docinfo.xml
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/controller/docinfo.xml
  downstream/titles/dev-guide/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/getting-started/docinfo.xml
  downstream/titles/hub/high-availability/docinfo.xml
  downstream/titles/hub/install/docinfo.xml
  downstream/titles/hub/manage-containers/docinfo.xml
  downstream/titles/hub/managing-user-access/docinfo.xml
  downstream/titles/hub/obtaining-token/docinfo.xml
  downstream/titles/hub/publishing-internal-content/docinfo.xml
  downstream/titles/hub/uploading-collections/docinfo.xml
  downstream/titles/hub/uploading-internal-collections/docinfo.xml
  downstream/titles/migration/docinfo.xml
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/upgrade/docinfo.xml
  downstream/titles/worker-install/docinfo.xml
Labels: backport to 2.1

#288 AAP-2328 Configuring external database for hub/controller on a AAP operator
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: AutomationPlatform, 2.1
