Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-06, with the labels that each got.

#353 Replace all Gb with GB for correctness and per style guide.
  downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc
  downstream/modules/platform/ref-hub-system-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/titles/hub/install/master.adoc
Labels: backport to 2.1, Backport to 2.2

#332 Aap 2007 AAP 2.1 on OCP Pre-Flight Check Documentation
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
  downstream/titles/aap-operator-installation/master.html
Labels: Peer review done

#350 AAP-589 Added instructions for deprovisioning isolated nodes and instance groups
  downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
  downstream/modules/platform/proc-deprovision-group.adoc
  downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc
Labels: 2.1, backport to 2.1, Backport to 2.2

#373 Added Python requirement to AAP docs
  downstream/modules/platform/con-aap-upgrade-prereq.adoc
  downstream/modules/platform/con-why-ee.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: backport to 2.1, Backport to 2.2

#372 AAP-2019 - Note and new topic for removing PVCs added
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-find-delete-PVCs.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
  downstream/titles/aap-operator-installation/master.html
Labels: Ready for peer review

#384 [2.2] AAP-4425 Updating version numbers in Upgrade & Migration guide
  downstream/assemblies/platform/assembly-content-migration.adoc
  downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
  downstream/modules/platform/con-aap-upgrade-prereq.adoc
  downstream/modules/platform/con-why-ee.adoc
  downstream/modules/platform/proc-upgrade-installer.adoc
Labels: 2.2, Ready for peer review

#354 AAP1808 - Added information for AWS storage class prereq
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
Labels: backport to 2.1, Backport to 2.2

#383 AAP-585 Importing CA certificates for automation mesh
  downstream/assemblies/platform/assembly-installing-automation-mesh.adoc
  downstream/assemblies/platform/assembly-mesh-design-patterns.adoc
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/modules/platform/con-install-mesh.adoc
  downstream/modules/platform/proc-defining-node-types.adoc
  downstream/modules/platform/proc-import-mesh-ca.adoc
  downstream/titles/automation-mesh/master.adoc
Labels: 2.1, 2.2, backport to 2.1, Backport to 2.2, Peer review done

#395 aap-4471 Fix service shape info
  downstream/modules/aap-on-azure/con-aap-azure-infrastructure-usage.adoc
  downstream/modules/platform/spare
Labels: backport to 2.1, Backport to 2.2, Peer review done

#402 AAP-4424: AAP 2.2 Install Guide Priority Updates (#388)
  downstream/assemblies/platform/assembly-migrate-platform.adoc
  downstream/modules/platform/con-cluster-platform-ext-database.adoc
  downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
  downstream/modules/platform/proc-attaching-subscriptions.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2, Backported to 2.2

#406 AAP-4102 HA Hub on SELinux (redo)
  downstream/assemblies/hub/assembly-deploying-high-availability-hub.adoc
  downstream/assemblies/hub/assembly-high-availability-hub-requirements.adoc
  downstream/assemblies/hub/assembly-installing-high-availability-hub.adoc
  downstream/modules/automation-hub/con-ha-hub-installation.adoc
  downstream/modules/automation-hub/con-network-storage-reqs.adoc
  downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
  downstream/titles/hub/high-availability/master.adoc
Labels: 2.1, 2.2, Ready for peer review
