Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-09, with the labels that each got.

#509 AAP-3713-Revised: Add directory info
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review

#513 [2.2] AAP-3713-Revised: Add directory info (509)
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Labels: 2.2, Backported to 2.2

#512 AAP-5155
  downstream/assemblies/platform/assembly-configure-known-proxies.adoc
  downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
  downstream/modules/platform/con-known-proxies.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2, Ready for peer review

#517 Corrected platform version
  downstream/modules/platform/proc-migrate-playbooks-roles.adoc
Labels: 2.2, Needs backport to 2.2

#519 Corrected typo
  downstream/modules/platform/ref-complex-mesh-topology.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2

#514 AAP-4697: Added traffic flow for ports and firewalls as well as new title
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/modules/platform/ref-access-control-requirements.adoc
  downstream/modules/platform/ref-network-ports-protocols.adoc
Labels: Automation Platform, 2.2, Needs backport to 2.2, Peer review complete

#522 AAP-4697: Added traffic flow for ports and firewalls as well as new title
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/modules/platform/ref-access-control-requirements.adoc
  downstream/modules/platform/ref-network-ports-protocols.adoc
Labels: Automation Platform, 2.2, Backported to 2.2, Ready for peer review

#493 AAP-2844 Add collections and content signing info
  downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
  downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: Peer review complete

#535 AAP-5740 Add attribute for console.redhat.com
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2, Peer review complete, attributes

#539 AAP-5802 Add common content to docs
  downstream/modules/aap-on-azure/aap-on-azure
  downstream/titles/catalog/getting-started/aap-common
  downstream/titles/catalog/getting-started/master.adoc
  downstream/titles/catalog/itsm-integration/aap-common
  downstream/titles/catalog/itsm-integration/master.adoc
  downstream/titles/catalog/lifecycle/aap-common
  downstream/titles/catalog/lifecycle/master.adoc
  downstream/titles/catalog/managing-products/aap-common
  downstream/titles/catalog/managing-products/master.adoc
  downstream/titles/catalog/onboarding/aap-common
  downstream/titles/catalog/onboarding/master.adoc
  downstream/titles/catalog/receptor/aap-common
  downstream/titles/catalog/receptor/master.adoc
  downstream/titles/catalog/support-matrix/aap-common
  downstream/titles/catalog/support-matrix/master.adoc
  downstream/titles/hub/configuring-galaxy-cli/aap-common
  downstream/titles/hub/configuring-galaxy-cli/master.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/aap-common
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
  downstream/titles/hub/faq/aap-common
  downstream/titles/hub/faq/master.adoc
  downstream/titles/hub/getting-started/aap-common
  downstream/titles/hub/getting-started/master.adoc
  downstream/titles/hub/high-availability/aap-common
  downstream/titles/hub/high-availability/master.adoc
  downstream/titles/hub/install/aap-common
  downstream/titles/hub/install/master.adoc
  downstream/titles/hub/lifecycle/aap-common
  downstream/titles/hub/lifecycle/master.adoc
  downstream/titles/hub/manage-containers/aap-common
  downstream/titles/hub/manage-containers/master.adoc
  downstream/titles/hub/managing-user-access/aap-common
  downstream/titles/hub/managing-user-access/master.adoc
  downstream/titles/hub/obtaining-token/aap-common
  downstream/titles/hub/obtaining-token/master.adoc
  downstream/titles/hub/publishing-internal-content/aap-common
  downstream/titles/hub/publishing-internal-content/master.adoc
  downstream/titles/hub/uploading-collections/aap-common
  downstream/titles/hub/uploading-collections/master.adoc
  downstream/titles/hub/uploading-internal-collections/aap-common
  downstream/titles/hub/uploading-internal-collections/master.adoc
  downstream/titles/migration/master.adoc
  release-notes/aap-common
  release-notes/master.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2, Ready for peer review

#461 Updated navigator installation method
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review

#548 Added new attributes
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2, attributes
