Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-10, with the labels that each got.

#547 AAP-2123 Improve automation mesh examples
  downstream/assemblies/platform/assembly-mesh-design-patterns.adoc
  downstream/images/mesh-multi-hop.png
  downstream/images/mesh-multiple-hybrid-nodes.png
  downstream/images/mesh-resilient-config.png
  downstream/images/mesh-segegrated-execution.png
  downstream/images/mesh-single-control-node.png
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-defining-node-types.adoc
  downstream/modules/platform/ref-control-plane-execution-topo-hop-nodes.adoc
  downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc
  downstream/modules/platform/ref-mesh-multi-hop-execution.adoc
  downstream/modules/platform/ref-mesh-segregated-execution_nodes.adoc
  downstream/modules/platform/ref-multiple-hybrid-nodes.adoc
  downstream/modules/platform/ref-single-node-control-plane-single-execution-node.adoc
  downstream/snippets/mesh-multi-hop.dot
  downstream/snippets/mesh-multiple-hybrid-nodes.dot
  downstream/snippets/mesh-resilient-config.dot
  downstream/snippets/mesh-segegrated-execution.dot
  downstream/snippets/mesh-single-control-node.dot
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/images
Labels: 2.2, Needs backport to 2.2, Not ready for peer review, Peer review complete, Ready for technical review, Automation mesh

#566 2.1 AAP-2123 Improve automation mesh examples (#547)
  downstream/assemblies/platform/assembly-mesh-design-patterns.adoc
  downstream/images/mesh-multi-hop.png
  downstream/images/mesh-multiple-hybrid-nodes.png
  downstream/images/mesh-resilient-config.png
  downstream/images/mesh-segegrated-execution.png
  downstream/images/mesh-single-control-node.png
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-defining-node-types.adoc
  downstream/modules/platform/ref-control-plane-execution-topo-hop-nodes.adoc
  downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc
  downstream/modules/platform/ref-mesh-multi-hop-execution.adoc
  downstream/modules/platform/ref-mesh-segregated-execution_nodes.adoc
  downstream/modules/platform/ref-multiple-hybrid-nodes.adoc
  downstream/modules/platform/ref-single-node-control-plane-single-execution-node.adoc
  downstream/snippets/mesh-multi-hop.dot
  downstream/snippets/mesh-multiple-hybrid-nodes.dot
  downstream/snippets/mesh-resilient-config.dot
  downstream/snippets/mesh-segegrated-execution.dot
  downstream/snippets/mesh-single-control-node.dot
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/images
Labels: Automation mesh

#570 Update attributes for cloud
  downstream/attributes/attributes.adoc
Labels: attributes

#556 AAP-1758 added note to set automationhub_upgrade flag to true
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: Needs backport to 2.2, Ready for peer review

#549 AAP-3678 - Added note for locating admin password
  downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
Labels: 2.1, 2.2, Needs backport to 2.1, Needs backport to 2.2, Ready for peer review, Needs backport to 2.0-ea

#538 AAP-4360 - Add section & info for AAP Operator to release notes for 2.2
  release-notes/master.adoc
  release-notes/topics/operator-220.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review

#460 AAP2336 - Created topics for Migration & Upgrade of Operator on OCP
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/modules/platform/con-aap-migration-considerations.adoc
  downstream/modules/platform/con-aap-migration-prepare.adoc
  downstream/modules/platform/con-aap-migration-prereqs.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
  downstream/modules/platform/proc-aap-create_controller.adoc
  downstream/modules/platform/proc-aap-create_hub.adoc
  downstream/modules/platform/proc-aap-migration-backup.adoc
  downstream/modules/platform/proc-aap-migration.adoc
  downstream/modules/platform/proc-create-postresql-secret.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-find-delete-PVCs.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-post-migration-cleanup.adoc
  downstream/modules/platform/proc-verify-network-connectivity.adoc
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review, Technical review complete

#575 Minor last minute correction to AAP-3675
  downstream/modules/platform/proc-install-aap-operator.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2

#583 Updated with two short notes for single and multi node cluster instal…
  downstream/modules/platform/ref-multi-node-cluster-installation.adoc
  downstream/modules/platform/ref-single-node-inventory.adoc
Labels: 2.1, 2.2, Needs backport to 2.1

#417 AAP-4364 - Restructure Builder Guide to create new EE Guide
  downstream/assemblies/builder/assembly-building-off-existing-ee.adoc
  downstream/assemblies/builder/assembly-definition-file-breakdown.adoc
  downstream/assemblies/builder/assembly-intro-to-builder.adoc
  downstream/assemblies/builder/assembly-publishing-exec-env.adoc
  downstream/assemblies/builder/assembly-using-builder.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc
  downstream/modules/automation-hub/proc-obtain-images.adoc
  downstream/modules/automation-hub/proc-pull-image.adoc
  downstream/modules/automation-hub/proc-push-container.adoc
  downstream/modules/automation-hub/proc-tag-pulled-image.adoc
  downstream/modules/builder/con-about-builder.adoc
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-additional-custom-build-steps.adoc
  downstream/modules/builder/con-ansible-config-file-path.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-definition-dependencies.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/con-why-builder.adoc
  downstream/modules/builder/con-why-ee.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/proc-pull-protected-registry.adoc
  downstream/modules/builder/ref-build-args-base-image.adoc
  downstream/titles/builder/docinfo.xml
  downstream/titles/builder/hub
  downstream/titles/builder/master.adoc
Labels: Needs backport to 2.2, Ready for peer review

#586 AAP-2336 Fix xref issues
  downstream/modules/platform/con-aap-migration-prepare.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/proc-aap-create_controller.adoc
  downstream/modules/platform/proc-aap-create_hub.adoc
  downstream/modules/platform/proc-aap-migration.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: Needs backport to 2.2, Peer review complete, Needs backport to 2.3

#582 Add summary of platform components
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/modules/platform/ref-platform-components.adoc
Labels: Needs backport to 2.2, Ready for peer review, Needs backport to 2.3

#555 Added new inventory file topics
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/assemblies/platform/assembly-multi-machine-install.adoc
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/assemblies/platform/assembly-platform-ext-database-install.adoc
  downstream/assemblies/platform/assembly-platform-non-inst-database.adoc
  downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc
  downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc
  downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc
  downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc
  downstream/modules/platform/con-declaring-variables.adoc
  downstream/modules/platform/con-editing-inventory-files.adoc
  downstream/modules/platform/con-inventory-introduction.adoc
  downstream/modules/platform/con-inventory-variables-intro.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-securing-secrets-in-inventory.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-catalog-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-deprovisioning.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-sso-variables.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Needs backport to 2.2, Ready for peer review, Ready for technical review, 2.3, Needs backport to 2.3

#592 AAP-2854 added prerequisites for controller and hub
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
Labels: 2.1

#595 Correct minor errors
  downstream/modules/platform/con-declaring-variables.adoc
  downstream/modules/platform/con-inventory-variables-intro.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3
