Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-12, with the labels that each got.

#656 AAP-357 added links to builder and navigator guides
  downstream/modules/core/con-execution-environments.adoc
  downstream/modules/dev-guide/con-content-workflows.adoc
Labels: 2.2, Needs backport to 2.2, Peer review complete, 2.3, Needs backport to 2.3

#660 Fixed formatting and spacing issues
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
  downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc
  downstream/modules/platform/proc-completing-post-installation-tasks.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Labels: 2.3

#668 AAP-4941 - Restructure of the AAP Install Guide
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/assemblies/platform/assembly-installing-aap-components.adoc
  downstream/assemblies/platform/assembly-multi-machine-cluster-scenario.adoc
  downstream/assemblies/platform/assembly-multi-machine-install.adoc
  downstream/assemblies/platform/assembly-platform-ext-database-install.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-single-machine-scenarios.adoc
  downstream/modules/platform/ref-controller-configs.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Docathon

#667 AAP-357 added links to builder and navigator guides (#656)
  downstream/modules/core/con-execution-environments.adoc
  downstream/modules/dev-guide/con-content-workflows.adoc
Labels: 2.2, Ready for peer review

#673 AAP-357 added links to builder and navigator guides (#656)
  downstream/modules/core/con-execution-environments.adoc
  downstream/modules/dev-guide/con-content-workflows.adoc
Labels: Ready for peer review, 2.3

#666 AAP-1644 updated old builder doc
  downstream/modules/builder/proc-customize-ee-image.adoc
Labels: 2.1, Ready for peer review

#674 AAP-7533 Docathon Section 1 of Operations Guide
  downstream/titles/aap-operations-guide/master.adoc
Labels: Docathon

#677 AAP-7538 docathon Modify Operations guide section 3 content
  downstream/assemblies/platform/assembly-controlling-data-collection.adoc
  downstream/modules/platform/con-user-data-tracking.adoc
  downstream/modules/platform/proc-control-data-collection.adoc
Labels: Docathon

#675 AAP-7531 Docathon Reordering and rearranging sections
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/modules/platform/con-editing-inventory-files.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Docathon

#679 AAP-7534B Updates to Chapter 2 of new Operations guide
  downstream/modules/platform/con-websocket-setup.adoc
  downstream/modules/platform/proc-configuring-discovery.adoc
Labels: Ready for peer review

#680 AAP-7547 - [docathon] Add install overview section and restructuring cleanup
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/con-aap-installation-overview.adoc
  downstream/modules/platform/con-aap-installation-prereqs.adoc
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
  downstream/modules/platform/proc-verify-controller-installation.adoc
  downstream/modules/platform/proc-verify-hub-installation.adoc
  downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
  downstream/modules/platform/ref-multi-node-cluster-installation.adoc
  downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
  downstream/modules/platform/ref-single-node-inventory.adoc
  downstream/modules/platform/ref-standalone-controller-ext-db.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Docathon

#684 AAP-7618 Include information regarding component options with AAP
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Docathon

#683 AAP-7617 Minor edits to new AAP Guides
  downstream/modules/platform/proc-attaching-subscriptions.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
Labels: Docathon

#698 Added cross reference
  downstream/modules/platform/con-editing-inventory-files.adoc
Labels: 2.3, Needs backport to 2.3

#702 Add release notes HTML files to .gitignore
  .gitignore
Labels: Needs backport to 2.1, Needs backport to 2.2, Needs backport to 2.3, repo

#704 IG-LINKFIX - changed hardcoded 2.3 in links to the PlatformVers
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/con-aap-installation-prereqs.adoc
  downstream/modules/platform/con-why-automation-mesh.adoc
  downstream/modules/platform/con-why-migrate-ansible-29.adoc
  downstream/modules/platform/con-why-migrate-ansible-core-212.adoc
  downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
  downstream/modules/platform/con-why-migrate-venvs-ee.adoc
  downstream/modules/platform/proc-verify-controller-installation.adoc
  downstream/modules/platform/proc-verify-hub-installation.adoc
  downstream/modules/platform/ref-controller-configs.adoc
  downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-hub-configs.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3

#712 Updated link in installation guide
  downstream/modules/platform/con-aap-installation-prereqs.adoc
Labels: Needs backport to 2.3

#714 Corrected description
  downstream/modules/automation-hub/con-ha-hub-installation.adoc
Labels: Needs backport to 2.3

#708 AAP-7802 - Created attribute to current product download page.
  downstream/assemblies/platform/assembly-installing-aap-components.adoc
  downstream/assemblies/platform/assembly-platform-ext-database-install.adoc
  downstream/assemblies/platform/assembly-platform-non-inst-database.adoc
  downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc
  downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc
  downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc
  downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-aap-installation-prereqs.adoc
Labels: Ready for peer review, attributes, 2.3, Needs backport to 2.3
