Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2022-11, with the labels that each got.

#600 Removed automationhub variable
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#587 AAP-1649: Adopt new Pulp RBAC
  downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
  downstream/modules/automation-hub/proc-assigning-roles.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
Labels: Automation Hub, Ready for peer review, 2.3, Needs backport to 2.3

#610 Modify builder title to match docinfo
  downstream/titles/builder/master.adoc
Labels: Needs backport to 2.2

#613 AAP-1649: Adopt new Pulp RBAC (#587)
  downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
  downstream/modules/automation-hub/proc-assigning-roles.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
Labels: Automation Hub, Ready for peer review, 2.3, Backported to 2.3

#603 AAP-6156 Updated EE storage location for controller
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Needs backport to 2.2, Ready for peer review, Technical review complete, Needs backport to 2.3

#564 Creating OCP performance guide
  downstream/assemblies/platform/assembly-control-plane-adjustments.adoc
  downstream/assemblies/platform/assembly-pod-spec-modifications.adoc
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-set-custom-pod-timeout.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
  downstream/titles/ocp_performance_guide/aap-common
  downstream/titles/ocp_performance_guide/aap_common
  downstream/titles/ocp_performance_guide/docinfo.xml
  downstream/titles/ocp_performance_guide/master.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#618 AAP-4928: Show how to download public key in AH UI
  downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
  downstream/modules/automation-hub/proc-downloading-signature-public-keys.adoc
Labels: Automation Hub, Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#625 AAP-4928: Show how to download public key in AH UI (#618)
  downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
  downstream/modules/automation-hub/proc-downloading-signature-public-keys.adoc
Labels: Automation Hub, Ready for peer review, 2.3, Backported to 2.3

#619 Aap 4667
  downstream/assemblies/hub/assembly-working-with-signed-containers.adoc
  downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc
  downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc
  downstream/titles/hub/manage-containers/master.adoc
Labels: Automation Hub, Ready for peer review, 2.3

#634 Replaced IP address with FQDN
  downstream/modules/platform/ref-single-node-inventory.adoc
  downstream/modules/platform/ref-standalone-controller-ext-db.adoc
Labels: Needs backport to 2.2, Ready for peer review, Needs backport to 2.3

#637 Corrected rpm install command
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#643 Add newline, brackets to fix install guide build failure
  downstream/titles/aap-installation-guide/master.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#646 Update release in docinfo only for docs in 2.3 (#641)
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-operator-backup/docinfo.xml
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/analytics/automation-savings-planner/docinfo.xml
  downstream/titles/analytics/automation-savings/docinfo.xml
  downstream/titles/analytics/job-explorer/docinfo.xml
  downstream/titles/analytics/reports/docinfo.xml
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/builder/docinfo.xml
  downstream/titles/catalog/getting-started/docinfo.xml
  downstream/titles/catalog/itsm-integration/docinfo.xml
  downstream/titles/catalog/support-matrix/docinfo.xml
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/dev-guide/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/getting-started/docinfo.xml
  downstream/titles/hub/high-availability/docinfo.xml
  downstream/titles/hub/install/docinfo.xml
  downstream/titles/hub/lifecycle/docinfo.xml
  downstream/titles/hub/manage-containers/docinfo.xml
  downstream/titles/hub/managing-user-access/docinfo.xml
  downstream/titles/hub/publishing-internal-content/docinfo.xml
  downstream/titles/hub/uploading-collections/docinfo.xml
  downstream/titles/hub/uploading-internal-collections/docinfo.xml
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/upgrade/docinfo.xml
  downstream/titles/worker-install/docinfo.xml
Labels: 2.3

#647 Fix build issues for 2.3 docs
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/uploading-collections/master.adoc
Labels: Needs backport to 2.3

#654 Update PlatformVers attribute
  downstream/attributes/attributes.adoc
Labels: attributes, 2.3
