Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-06, with the labels that each got.

#1047 2.3 Added description of one-way communication to mesh (#919)
  downstream/assemblies/platform/assembly-mesh-design-patterns.adoc
  downstream/images/mesh-one-way-communication.png
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-mesh-one-way-communication.adoc
Labels: 2.3

#1052 AAP-12753A Deleted extra EDA attributes added previously.
  downstream/attributes/attributes.adoc
Labels: Ready for peer review, Needs backport to 2.4

#1037 [2.4] AAP-8366: Recommend using fully updated nodes to install AAP (#1029)
  downstream/modules/platform/con-aap-installation-prereqs.adoc
Labels: Not ready for peer review, 2.4, Backported to 2.4

#1034 AAP-7106 - Create document for P1 Repository Management features
  downstream/assemblies/hub/assembly-basic-remote-management.adoc
  downstream/assemblies/hub/assembly-basic-repo-management.adoc
  downstream/assemblies/hub/assembly-collection-import-export.adoc
  downstream/assemblies/hub/assembly-remote-management.adoc
  downstream/assemblies/hub/assembly-repo-management.adoc
  downstream/assemblies/hub/assembly-repo-sync.adoc
  downstream/modules/automation-hub/con-approval-pipeline.adoc
  downstream/modules/automation-hub/con-repo-rbac.adoc
  downstream/modules/automation-hub/proc-adding-collections-repository.adoc
  downstream/modules/automation-hub/proc-basic-repo-sync.adoc
  downstream/modules/automation-hub/proc-create-remote.adoc
  downstream/modules/automation-hub/proc-create-repository.adoc
  downstream/modules/automation-hub/proc-export-collection.adoc
  downstream/modules/automation-hub/proc-import-collection.adoc
  downstream/modules/automation-hub/proc-provide-remote-access.adoc
  downstream/modules/automation-hub/proc-provide-repository-access.adoc
  downstream/modules/automation-hub/proc-revert-repository-version.adoc
  downstream/titles/hub/repo-management/aap-common
  downstream/titles/hub/repo-management/attributes
  downstream/titles/hub/repo-management/docinfo.xml
  downstream/titles/hub/repo-management/hub
  downstream/titles/hub/repo-management/images
  downstream/titles/hub/repo-management/master.adoc
Labels: Automation Hub, 2.4, Needs backport to 2.4

#1061 JIRA-AAP-4359: Added the scenario to import or generate API tokens in AAP installer
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: 2.1, 2.2, Ready for peer review, 2.3, 2.4

#1063 [Backport] - AAP-7106 - Create document for P1 Repository Management features (#1034)
  downstream/assemblies/hub/assembly-basic-remote-management.adoc
  downstream/assemblies/hub/assembly-basic-repo-management.adoc
  downstream/assemblies/hub/assembly-collection-import-export.adoc
  downstream/assemblies/hub/assembly-remote-management.adoc
  downstream/assemblies/hub/assembly-repo-management.adoc
  downstream/assemblies/hub/assembly-repo-sync.adoc
  downstream/modules/automation-hub/con-approval-pipeline.adoc
  downstream/modules/automation-hub/con-repo-rbac.adoc
  downstream/modules/automation-hub/proc-adding-collections-repository.adoc
  downstream/modules/automation-hub/proc-basic-repo-sync.adoc
  downstream/modules/automation-hub/proc-create-remote.adoc
  downstream/modules/automation-hub/proc-create-repository.adoc
  downstream/modules/automation-hub/proc-export-collection.adoc
  downstream/modules/automation-hub/proc-import-collection.adoc
  downstream/modules/automation-hub/proc-provide-remote-access.adoc
  downstream/modules/automation-hub/proc-provide-repository-access.adoc
  downstream/modules/automation-hub/proc-revert-repository-version.adoc
  downstream/titles/hub/repo-management/aap-common
  downstream/titles/hub/repo-management/attributes
  downstream/titles/hub/repo-management/docinfo.xml
  downstream/titles/hub/repo-management/hub
  downstream/titles/hub/repo-management/images
  downstream/titles/hub/repo-management/master.adoc
Labels: Ready for peer review, 2.4

#1059 AAP-1636: New AAP Hardening Guide
  downstream/assemblies/aap-hardening/aap-hardening
  downstream/assemblies/aap-hardening/assembly-aap-compliance.adoc
  downstream/assemblies/aap-hardening/assembly-aap-security-enabling.adoc
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/titles/aap-hardening/aap-common
  downstream/titles/aap-hardening/aap-hardening
  downstream/titles/aap-hardening/attributes
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-hardening/images
  downstream/titles/aap-hardening/master.adoc
Labels: AAP Hardening

#1055 Corrected minimum and required ansible versions
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2, Needs backport to 2.2, 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#1056 2.2 Updated Ansible version AAP-11993 for 2.2
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2

#1057 Updated ansible version AAP-11993 for 2.3
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.3

#1066 2.4 Corrected minimum and required ansible versions (#1055)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.4

#1067 AAP-12684 Add direct doc feedback module to repo management doc
  downstream/titles/hub/repo-management/master.adoc
Labels: Needs backport to 2.4

#1062 AAP-12616 add instructions for updating execution environment images …
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
Labels: Ready for peer review, 2.3, 2.4

#1069 AAP-1636-fix: Reorder of titles
  downstream/titles/aap-hardening/master.adoc
Labels: Ready for peer review, 2.4, AAP Hardening

#1070 backport 2.4: AAP-12616 add instructions for updating execution environment images …
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
Labels: Ready for peer review, Technical review complete, 2.4

#1071 backport 2.3: AAP-12616 add instructions for updating execution environment images …
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
Labels: Ready for peer review, Technical review complete, 2.3

#1072 Updated steps for new role permissions
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
Labels: Ready for peer review, Needs backport to 2.3, Needs backport to 2.4

#1074 [2.4] AAP-1636: New AAP Hardening Guide (#1059)
  downstream/assemblies/aap-hardening/aap-hardening
  downstream/assemblies/aap-hardening/assembly-aap-compliance.adoc
  downstream/assemblies/aap-hardening/assembly-aap-security-enabling.adoc
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/titles/aap-hardening/aap-common
  downstream/titles/aap-hardening/aap-hardening
  downstream/titles/aap-hardening/attributes
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-hardening/images
  downstream/titles/aap-hardening/master.adoc
Labels: 2.4, AAP Hardening

#1079 Backport 2.4 1072
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
Labels: Ready for peer review, 2.4

#1078 Backport 2.3 1072
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
Labels: Ready for peer review, Backported to 2.3

#1026 Creating EDA user guide
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
  downstream/assemblies/eda/eda
  downstream/attributes/attributes.adoc
  downstream/modules/eda/proc-eda-activate-webhook.adoc
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
  downstream/modules/eda/proc-eda-set-up-new-project.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
  downstream/modules/eda/proc-eda-set-up-token.adoc
  downstream/modules/eda/proc-eda-test-with-K8s.adoc
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: Peer review complete, Technical review complete, 2.4

#1088 Fix tag in docinfo.xml
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/upgrade/docinfo.xml
Labels: Needs backport to 2.4

#1042 AAP-10975A Add installation-related content to the AAP Planning Guide
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
  downstream/modules/platform/con-about-eda-controller.adoc
  downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for peer review, Technical review complete, Needs backport to 2.4

#1050 AAP-10975C New chapter on EDA installation w/ AAP operator on OCP
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: Ready for peer review, Technical review complete, Needs backport to 2.4

#1090 Created new content for synching images.
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/modules/automation-hub/proc-sync-image.adoc
Labels: Ready for peer review, Needs backport to 2.3, Needs backport to 2.4

#1068 Add chapter on password encryption
  downstream/assemblies/platform/assembly-encrypting-plaintext-passwords.adoc
  downstream/modules/platform/proc-create-password-hashes.adoc
  downstream/modules/platform/proc-encrypt-postgres-password.adoc
  downstream/modules/platform/proc-restart-controller-services.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for peer review, 2.4, Needs backport to 2.4

#1094 2.4 Add chapter on password encryption (#1068)
  downstream/assemblies/platform/assembly-encrypting-plaintext-passwords.adoc
  downstream/modules/platform/proc-create-password-hashes.adoc
  downstream/modules/platform/proc-encrypt-postgres-password.adoc
  downstream/modules/platform/proc-restart-controller-services.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: 2.4

#1095 Created new content for synching images. (#1090)
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/modules/automation-hub/proc-sync-image.adoc
Labels: Ready for peer review, Backported to 2.3

#1092 AAP-13402 update automation hub variables
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#1051 AAP-12885 Update docs to reflect UI changes for automation hub
  downstream/assemblies/hub/assembly-managing-container-registry.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/automation-hub/con-container-registry.adoc
  downstream/modules/automation-hub/con-remote-repos.adoc
  downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/automation-hub/proc-create-api-token.adoc
  downstream/modules/automation-hub/proc-create-content-developers.adoc
  downstream/modules/automation-hub/proc-create-namespace.adoc
  downstream/modules/automation-hub/proc-create-synclist.adoc
  downstream/modules/automation-hub/proc-create-users.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-delete-user.adoc
  downstream/modules/automation-hub/proc-edit-namespace.adoc
  downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc
  downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/automation-hub/proc-review-collection-imports.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
  downstream/modules/automation-hub/proc-uploading-collections.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: Automation Hub, Ready for technical review, 2.4, Needs backport to 2.4

#1113 2.4 Update download URL attribute for 2.4 (#1111)
  downstream/attributes/attributes.adoc
Labels: 2.4

#948 Added inventory variable
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Ready for technical review, 2.3, Needs backport to 2.3

#1105 AAP-4830 added new line to assembly file, and added new proc doc to m…
  downstream/assemblies/central-auth/assembly-configuring-central-auth-generic-oidc-settings.adoc
  downstream/assemblies/platform/assembly-content-migration.adoc
  downstream/assemblies/platform/assembly-converting-playbooks-for-aap2.adoc
  downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
  downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
  downstream/modules/platform/proc-install-ansible-colls.adoc
  downstream/modules/platform/ref-converting-playbook-examples.adoc
  downstream/titles/central-auth/master.adoc
  downstream/titles/upgrade/master.adoc
Labels: Not ready for peer review

#1148 2.4 Fixed icon size (#1147)
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/automation-hub/con-remote-repos.adoc
  downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
Labels: 2.4

#1144 Fix broken links that use PlatformVers attribute in 2.4 docs
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/modules/dev-guide/con-content-workflows.adoc
  downstream/modules/platform/con-aap-upgrade-prereq.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
  downstream/modules/platform/proc-upgrade-installer.adoc
  downstream/modules/platform/ref-hub-configs.adoc
  downstream/titles/hub/install/master.adoc
Labels: Ready for peer review, 2.4

#1152 Changed icons in user guide
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Labels: Ready for technical review, 2.4, Needs backport to 2.4

#1153 Changed icons in user guide (#1152)
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Labels: 2.4

#1154 Corrected Release Notes formatting
  downstream/titles/release-notes/topics/aap-23.adoc
Labels: 2.4, Needs backport to 2.4

#1155 Corrected Release Notes formatting (#1154)
  downstream/titles/release-notes/topics/aap-23.adoc
Labels: 2.4

#1157 Corrected Ansible version
  downstream/titles/hub/install/master.adoc
Labels: 2.4, Needs backport to 2.4

#1158 Corrected Ansible version (#1157)
  downstream/titles/hub/install/master.adoc
Labels: 2.4

#1160 Corrected Ansible version for 2.3
  downstream/titles/hub/install/master.adoc
Labels: 2.3

#1163 AAP-12257-rn: Fixed broken links in AAP 2.4 release notes
  downstream/titles/release-notes/topics/aap-24.adoc
  downstream/titles/release-notes/topics/controller-440.adoc
  downstream/titles/release-notes/topics/docs-24.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: Ready for peer review, 2.4

#1164 Backport pull request #1163 from main to 2.4
  downstream/titles/release-notes/topics/aap-24.adoc
  downstream/titles/release-notes/topics/controller-440.adoc
  downstream/titles/release-notes/topics/docs-24.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: Ready for peer review, 2.4

#1167 Use unicode characters for icons (#1161)
  .gitignore
  downstream/archive/archived-images/cog.png
  downstream/archive/archived-images/ellipsis.png
  downstream/archive/archived-images/more_actions.png
  downstream/archive/archived-modules/catalog/proc_Comment_on_request.adoc
  downstream/archive/archived-titles/catalog/getting-started/master.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/analytics/proc-edit-savings-plan.adoc
  downstream/modules/analytics/proc-link-plan-job-template.adoc
  downstream/modules/automation-hub/proc-adding-collections-repository.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-delete-container.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/automation-hub/proc-delete-user.adoc
  downstream/modules/automation-hub/proc-edit-namespace.adoc
  downstream/modules/automation-hub/proc-provide-remote-access.adoc
  downstream/modules/automation-hub/proc-provide-repository-access.adoc
  downstream/modules/automation-hub/proc-revert-repository-version.adoc
  downstream/modules/automation-hub/proc-review-collection-imports.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
  downstream/modules/automation-hub/proc-tag-image.adoc
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
Labels: attributes, 2.4

#1168 Corrected assembly names and include statement
  downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
  downstream/titles/upgrade/master.adoc
Labels: 2.4, Needs backport to 2.4

#1170 Corrected assembly names and include statement (#1168)
  downstream/assemblies/platform/assembly-converting-playbooks-for-aap2.adoc
  downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
  downstream/modules/platform/ref-converting-playbook-examples.adoc
  downstream/titles/upgrade/master.adoc
Labels: 2.4

#1176 2.4 AAP-13660 Fix formatting issues in 2.4 Upgrade guide (#1175)
  downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
Labels: 2.4
