Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-05, with the labels that each got.

#987 AAP-11399 Add list of published 2.4 docs to snippets folder
  downstream/snippets/published-24.txt
Labels: 2.4, Needs backport to 2.4

#941 [WIP] AAP-2079: Add AAP architectural diagram
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/ansible-network-ports-protocols.png
Labels: Automation Platform, 2.2, Needs backport to 2.2, Peer review complete, Technical review complete, 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#978 AAP-11409 updated link for Red Hat Ansible Automation Platform Produc…
  downstream/assemblies/platform/assembly-platform-non-inst-database.adoc
Labels: 2.2, Ready for peer review, Technical review complete

#992 AAP-11399 Add list of published 2.4 docs to snippets folder (#987)
  downstream/snippets/published-24.txt
Labels: 2.4, snippets

#993 AAP-11409 updated link for Red Hat Ansible Automation Platform Produc…
  downstream/assemblies/platform/assembly-platform-non-inst-database.adoc
Labels: 2.2, Ready for peer review

#989 2.2 AAP-9897 updated section 2.1 (#977)
  downstream/images/search-icon.png
  downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
  downstream/titles/hub/configuring-galaxy-cli/master.adoc
  downstream/titles/hub/getting-started/master.adoc
Labels: 2.2

#990 2.1 AAP-9897 updated section 2.1 (#977)
  downstream/images/search-icon.png
  downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
  downstream/titles/hub/configuring-galaxy-cli/master.adoc
  downstream/titles/hub/getting-started/master.adoc
Labels: 2.1, Ready for peer review

#994 2.4 AAP-9897 updated Hub Getting started guide section 2.1 (#977)
  downstream/images/search-icon.png
  downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
  downstream/titles/hub/configuring-galaxy-cli/master.adoc
  downstream/titles/hub/getting-started/master.adoc
Labels: 2.4

#999 Adding changes for AAP4381 to the 2.2 branch
  downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: 2.2, Ready for peer review

#985 Backport-2.3-980 New content on LDAP configuration for private automation hub
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: Peer review complete, 2.3, Backported to 2.3

#996 AAP-11647 updated table 4.10 Automation hub (#986)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.4

#1001 AAP-11313 - added information regarding configuration of Hub connection
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
Labels: Ready for technical review, 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#998 2.3 AAP-2079: Add AAP Architectural Diagram (#941)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/ansible-network-ports-protocols.png
Labels: Ready for peer review, 2.3, Backported to 2.3

#995 AAP-2079: Add AAP architectural diagram (#941)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/ansible-network-ports-protocols.png
Labels: Ready for peer review, 2.4, Backported to 2.4

#1017 2.4 AAP-10050 Move release notes into titles directory and update sync script
  bin/sync_docs.sh
  downstream/titles/release-notes/.gitkeep
  downstream/titles/release-notes/aap-common
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/.gitkeep
  downstream/titles/release-notes/topics/aap-126.adoc
  downstream/titles/release-notes/topics/aap-21.adoc
  downstream/titles/release-notes/topics/aap-211.adoc
  downstream/titles/release-notes/topics/aap-212.adoc
  downstream/titles/release-notes/topics/aap-213.adoc
  downstream/titles/release-notes/topics/aap-214.adoc
  downstream/titles/release-notes/topics/aap-22.adoc
  downstream/titles/release-notes/topics/aap-221.adoc
  downstream/titles/release-notes/topics/aap-23.adoc
  downstream/titles/release-notes/topics/bugfixes-022020.adoc
  downstream/titles/release-notes/topics/bugfixes-052020.adoc
  downstream/titles/release-notes/topics/bugfixes-102020.adoc
  downstream/titles/release-notes/topics/catalog-05-2022.adoc
  downstream/titles/release-notes/topics/catalog-11-2020.adoc
  downstream/titles/release-notes/topics/catalog-11-2022.adoc
  downstream/titles/release-notes/topics/changelog-022020.adoc
  downstream/titles/release-notes/topics/controller-41.adoc
  downstream/titles/release-notes/topics/controller-411.adoc
  downstream/titles/release-notes/topics/controller-414.adoc
  downstream/titles/release-notes/topics/controller-420.adoc
  downstream/titles/release-notes/topics/controller-430.adoc
  downstream/titles/release-notes/topics/docs-23.adoc
  downstream/titles/release-notes/topics/enhancements-052020.adoc
  downstream/titles/release-notes/topics/enhancements-102020.adoc
  downstream/titles/release-notes/topics/enhancements.adoc
  downstream/titles/release-notes/topics/hub-42.adoc
  downstream/titles/release-notes/topics/hub-421.adoc
  downstream/titles/release-notes/topics/hub-422.adoc
  downstream/titles/release-notes/topics/hub-423.adoc
  downstream/titles/release-notes/topics/hub-424.adoc
  downstream/titles/release-notes/topics/hub-426.adoc
  downstream/titles/release-notes/topics/hub-441.adoc
  downstream/titles/release-notes/topics/hub-443.adoc
  downstream/titles/release-notes/topics/hub-450.adoc
  downstream/titles/release-notes/topics/hub-460.adoc
  downstream/titles/release-notes/topics/insights-062021.adoc
  downstream/titles/release-notes/topics/insights-102021.adoc
  downstream/titles/release-notes/topics/introduction.adoc
  downstream/titles/release-notes/topics/new-features-feb-2020.adoc
  downstream/titles/release-notes/topics/new-features-may-2020.adoc
  downstream/titles/release-notes/topics/new-features-oct-2020.adoc
  downstream/titles/release-notes/topics/operator-220.adoc
  downstream/titles/release-notes/topics/operator-230.adoc
  downstream/titles/release-notes/topics/platform-installer-121.adoc
  downstream/titles/release-notes/topics/platform-intro-124.adoc
  downstream/titles/release-notes/topics/platform-intro-125.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
  downstream/titles/release-notes/topics/tower-intro-38.adoc
  downstream/titles/release-notes/topics/tower-intro-381.adoc
  downstream/titles/release-notes/topics/tower-intro-382.adoc
  downstream/titles/release-notes/topics/tower-intro-383.adoc
  downstream/titles/release-notes/topics/tower-intro-384.adoc
  downstream/titles/release-notes/topics/upgrading.adoc
Labels: Release notes, repo, 2.4

#1019 Update version in 2.4 release notes
  downstream/titles/release-notes/docinfo.xml
Labels: Release notes, 2.4, Needs backport to 2.4

#1021 AAP-10050 Delete release notes from downstream folder
  downstream/release-notes/.gitkeep
  downstream/release-notes/aap-common
  downstream/release-notes/docinfo.xml
  downstream/release-notes/master.adoc
  downstream/release-notes/topics/.gitkeep
  downstream/release-notes/topics/aap-126.adoc
  downstream/release-notes/topics/aap-21.adoc
  downstream/release-notes/topics/aap-211.adoc
  downstream/release-notes/topics/aap-212.adoc
  downstream/release-notes/topics/aap-213.adoc
  downstream/release-notes/topics/aap-214.adoc
  downstream/release-notes/topics/aap-22.adoc
  downstream/release-notes/topics/aap-221.adoc
  downstream/release-notes/topics/aap-23.adoc
  downstream/release-notes/topics/bugfixes-022020.adoc
  downstream/release-notes/topics/bugfixes-052020.adoc
  downstream/release-notes/topics/bugfixes-102020.adoc
  downstream/release-notes/topics/catalog-05-2022.adoc
  downstream/release-notes/topics/catalog-11-2020.adoc
  downstream/release-notes/topics/catalog-11-2022.adoc
  downstream/release-notes/topics/changelog-022020.adoc
  downstream/release-notes/topics/controller-41.adoc
  downstream/release-notes/topics/controller-411.adoc
  downstream/release-notes/topics/controller-414.adoc
  downstream/release-notes/topics/controller-420.adoc
  downstream/release-notes/topics/controller-430.adoc
  downstream/release-notes/topics/docs-23.adoc
  downstream/release-notes/topics/enhancements-052020.adoc
  downstream/release-notes/topics/enhancements-102020.adoc
  downstream/release-notes/topics/enhancements.adoc
  downstream/release-notes/topics/hub-42.adoc
  downstream/release-notes/topics/hub-421.adoc
  downstream/release-notes/topics/hub-422.adoc
  downstream/release-notes/topics/hub-423.adoc
  downstream/release-notes/topics/hub-424.adoc
  downstream/release-notes/topics/hub-426.adoc
  downstream/release-notes/topics/hub-441.adoc
  downstream/release-notes/topics/hub-443.adoc
  downstream/release-notes/topics/hub-450.adoc
  downstream/release-notes/topics/hub-460.adoc
  downstream/release-notes/topics/insights-062021.adoc
  downstream/release-notes/topics/insights-102021.adoc
  downstream/release-notes/topics/introduction.adoc
  downstream/release-notes/topics/new-features-feb-2020.adoc
  downstream/release-notes/topics/new-features-may-2020.adoc
  downstream/release-notes/topics/new-features-oct-2020.adoc
  downstream/release-notes/topics/operator-220.adoc
  downstream/release-notes/topics/operator-230.adoc
  downstream/release-notes/topics/platform-installer-121.adoc
  downstream/release-notes/topics/platform-intro-124.adoc
  downstream/release-notes/topics/platform-intro-125.adoc
  downstream/release-notes/topics/platform-intro.adoc
  downstream/release-notes/topics/tower-intro-38.adoc
  downstream/release-notes/topics/tower-intro-381.adoc
  downstream/release-notes/topics/tower-intro-382.adoc
  downstream/release-notes/topics/tower-intro-383.adoc
  downstream/release-notes/topics/tower-intro-384.adoc
  downstream/release-notes/topics/upgrading.adoc
Labels: Release notes

#966 Added instructions for adding content
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/automation-hub/con-rh-certified-synclist.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3, 2.4

#1027 AAP-12313: adds an underscore to an automation controller variable
  downstream/modules/platform/ref-controller-variables.adoc
Labels: Controller, Ready for peer review, 2.3, 2.4

#1028 Added instructions for adding content (#966)
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/automation-hub/con-rh-certified-synclist.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: 2.4

#1029 AAP-8366: Recommend using fully updated nodes to install AAP
  downstream/modules/platform/con-aap-installation-prereqs.adoc
Labels: Automation Platform, 2.2, Needs backport to 2.2, Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#973 Added information about requirements file.
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc
  downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
Labels: Ready for technical review, 2.4

#1039 AAP-12541 - Update procedure for enabling the repo
  downstream/modules/builder/proc-installing-builder.adoc
Labels: Needs backport to 2.2, Ready for technical review, 2.3, Needs backport to 2.3

#1040 AAP-12573 Remove remaining references to automation services catalog
  downstream/archive/archived-modules/platform/con-about-services-catalog.adoc
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Catalog, Ready for peer review, 2.4, ARCHIVE
