Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-04, with the labels that each got.

#822 AAP-6074 added subscription manifest procedures to activate aap
  downstream/assemblies/platform/assembly-aap-activate.adoc
  downstream/assemblies/platform/assembly-aap-manifest-files.adoc
  downstream/assemblies/platform/assembly-aap-post-installation.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-aap-add-merge-subscriptions.adoc
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Not ready for peer review, Ready for technical review, 2.3, Needs backport to 2.3

#940 AAP-10662 Update AAP version to 2.4
  downstream/attributes/attributes.adoc
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-operations-guide/docinfo.xml
  downstream/titles/aap-operator-backup/docinfo.xml
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/aap-planning-guide/docinfo.xml
  downstream/titles/analytics/automation-savings-planner/docinfo.xml
  downstream/titles/analytics/automation-savings/docinfo.xml
  downstream/titles/analytics/job-explorer/docinfo.xml
  downstream/titles/analytics/reports/docinfo.xml
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/builder/docinfo.xml
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/dev-guide/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/getting-started/docinfo.xml
  downstream/titles/hub/high-availability/docinfo.xml
  downstream/titles/hub/install/docinfo.xml
  downstream/titles/hub/lifecycle/docinfo.xml
  downstream/titles/hub/manage-containers/docinfo.xml
  downstream/titles/hub/managing-user-access/docinfo.xml
  downstream/titles/hub/publishing-internal-content/docinfo.xml
  downstream/titles/hub/uploading-collections/docinfo.xml
  downstream/titles/hub/uploading-internal-collections/docinfo.xml
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/ocp_performance_guide/docinfo.xml
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/upgrade/docinfo.xml
Labels: Peer review complete, attributes, Version, 2.4

#944 AAP-9671 updated Introduction (#932)
  downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Labels: 2.1, Ready for peer review

#945 AAP-9671 updated Introduction (#932)
  downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Labels: 2.2, Ready for peer review

#946 AAP-5422 Z-Stream release notes 2.1.4
  release-notes/master.adoc
  release-notes/master.html
  release-notes/topics/aap-214.adoc
  release-notes/topics/controller-414.adoc
  release-notes/topics/hub-443.adoc
Labels: Release notes, Ready for peer review, Technical review complete, 2.3

#829 AAP-4587 Add info for connecting hub to existing SSO
  downstream/assemblies/hub/assembly-hub-connect-sso.adoc
  downstream/assemblies/hub/assembly-hub-install-setup-script.adoc
  downstream/modules/automation-hub/proc-run-setup-script-hub.adoc
  downstream/modules/automation-hub/proc-verify-sso-install.adoc
  downstream/modules/automation-hub/ref-variables-connect-hub-sso.adoc
  downstream/titles/hub/getting-started/hub
  downstream/titles/hub/getting-started/master.adoc
  downstream/titles/hub/install/images
  downstream/titles/hub/install/master.adoc
Labels: Ready for peer review

#947 Corrected Keycloak client instructions
  downstream/modules/platform/proc-create-keycloak-client.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3, 2.4

#952 2.3 Corrected Keycloak client instructions (#947)
  downstream/modules/platform/proc-create-keycloak-client.adoc
Labels: 2.3

#943 Editing hub documents
  downstream/assemblies/hub/assembly-working-with-namespaces.adoc
  downstream/modules/automation-hub/con-namespaces.adoc
  downstream/modules/automation-hub/proc-create-content-developers.adoc
  downstream/modules/automation-hub/proc-create-namespace.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/automation-hub/proc-edit-namespace.adoc
  downstream/modules/automation-hub/proc-review-collection-imports.adoc
  downstream/modules/automation-hub/proc-uploading-collections.adoc
  downstream/titles/hub/uploading-internal-collections/master.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3

#955 AAP-5422 Z-Stream release notes 2.1.4 (#946)
  release-notes/master.adoc
  release-notes/master.html
  release-notes/topics/aap-214.adoc
  release-notes/topics/controller-414.adoc
  release-notes/topics/hub-443.adoc
Labels: 2.1, Ready for peer review

#949 AAP-5422 Z-Stream release notes 2.1.4 (#946)
  release-notes/master.adoc
  release-notes/master.html
  release-notes/topics/aap-214.adoc
  release-notes/topics/controller-414.adoc
  release-notes/topics/hub-443.adoc
Labels: Release notes, Ready for peer review, 2.3

#957 Fix image ref in analytics module
  downstream/modules/analytics/proc-link-plan-job-template.adoc
Labels: Needs backport to 2.1, Needs backport to 2.2, Ready for peer review, Needs backport to 2.3

#960 2.3 Fix image ref in analytics module
  downstream/modules/analytics/proc-link-plan-job-template.adoc
Labels: 2.3

#958 2.1 Fix image ref in analytics module
  downstream/modules/analytics/proc-link-plan-job-template.adoc
Labels: 2.1

#968 2.3 AAP-4587 Add info for connecting hub to existing SSO (#829)
  downstream/assemblies/hub/assembly-hub-connect-sso.adoc
  downstream/assemblies/hub/assembly-hub-install-setup-script.adoc
  downstream/modules/automation-hub/proc-run-setup-script-hub.adoc
  downstream/modules/automation-hub/proc-verify-sso-install.adoc
  downstream/modules/automation-hub/ref-variables-connect-hub-sso.adoc
  downstream/titles/hub/getting-started/hub
  downstream/titles/hub/getting-started/master.adoc
  downstream/titles/hub/install/images
  downstream/titles/hub/install/master.adoc
Labels: 2.3

#963 [AAP-11277] Hub document edits
  downstream/assemblies/hub/assembly-managing-private-collections.adoc
  downstream/modules/automation-hub/con-approval.adoc
  downstream/modules/automation-hub/proc-reject-collections.adoc
  downstream/titles/hub/publishing-internal-content/master.adoc
Labels: Needs backport to 2.2, Ready for peer review, Needs backport to 2.3, 2.4

#965 [Backport] AAP-6074 added subscription manifest procedures to activate aap (#822)
  downstream/assemblies/platform/assembly-aap-activate.adoc
  downstream/assemblies/platform/assembly-aap-manifest-files.adoc
  downstream/assemblies/platform/assembly-aap-post-installation.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-aap-add-merge-subscriptions.adoc
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for peer review

#976 AAP-11388 Add sync script for AAP 2.4
  bin/sync_docs.sh
  bin/sync_ocp_latest.sh
Labels: 2.4

#979 Adding missing attributes
  downstream/assemblies/hub/assembly-hub-connect-sso.adoc
  downstream/modules/automation-hub/proc-run-setup-script-hub.adoc
  downstream/titles/hub/install/master.adoc
Labels: Needs backport to 2.2, Ready for peer review, Needs backport to 2.3, 2.4

#977 AAP-9897 updated section 2.1
  downstream/images/search-icon.png
  downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
  downstream/titles/hub/configuring-galaxy-cli/master.adoc
Labels: Ready for peer review, Peer review complete, Technical review complete, 2.3
