Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-02, with the labels that each got.

#779 AAP-8472 updated version numbers within Deploying the Red Hat Ansible…
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
Labels: Ready for peer review, Technical review complete, 2.3

#807 Fix images path in hub module
  downstream/modules/automation-hub/proc-edit-namespace.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#810 Fix master.adoc attributes for configuring-private-hub-rh-certified
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: Ready for peer review

#800 AAP-8472 updated version numbers within Deploying the Red Hat Ansible…
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
Labels: Ready for peer review, 2.3

#788 AAP-8656 updated version numbers across document
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#818 AAP-4882 Added link to the Pulp file system layout to Ch 2.2 Add'l resources
  downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Labels: 2.2, Needs backport to 2.2, Peer review complete

#819 Added information on builds
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/ref-build-args-base-image.adoc
Labels: Needs backport to 2.2, Ready for peer review, Technical review complete, Needs backport to 2.3

#823 Correct statement about database location
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#824 Correct statement about database location
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: 2.3

#825 Correct statement about database location
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: 2.2

#833 AAP-4206: Add alt-text to images
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/con-navigator-modes.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-execute-playbook-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/security/con-automate-idps-rules.adoc
  downstream/modules/security/con-automating-firewall-rules.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
  downstream/modules/security/proc-deleting-firewall-rule.adoc
Labels: 2.1, 2.2, 2.3

#834 Add further information to inventory file sections (#783)
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-sso-variables.adoc
Labels: Backported to 2.3

#736 Changes to inventory file information
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: Ready for peer review, Technical review complete, Needs backport to 2.3

#836 2.3 Changes to inventory file information (#736)
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: 2.3

#826 2.3 AAP-9027 Archive unpublished 2.3 title directories and add snippet for published titles
  archive/archived-titles/aap-on-aws/aap-common
  archive/archived-titles/aap-on-aws/aap-on-aws
  archive/archived-titles/aap-on-aws/attributes
  archive/archived-titles/aap-on-aws/docinfo.xml
  archive/archived-titles/aap-on-aws/images
  archive/archived-titles/aap-on-aws/master.adoc
  archive/archived-titles/aap-on-azure/aap-common
  archive/archived-titles/aap-on-azure/aap-on-azure
  archive/archived-titles/aap-on-azure/attributes
  archive/archived-titles/aap-on-azure/docinfo.xml
  archive/archived-titles/aap-on-azure/images
  archive/archived-titles/aap-on-azure/master.adoc
  archive/archived-titles/aap-on-azure/master.html
  archive/archived-titles/analytics/user-access/aap-common
  archive/archived-titles/analytics/user-access/analytics
  archive/archived-titles/analytics/user-access/attributes
  archive/archived-titles/analytics/user-access/docinfo.xml
  archive/archived-titles/analytics/user-access/images
  archive/archived-titles/analytics/user-access/master.adoc
  archive/archived-titles/catalog/lifecycle/.gitkeep
  archive/archived-titles/catalog/lifecycle/aap-common
  archive/archived-titles/catalog/lifecycle/docinfo.xml
  archive/archived-titles/catalog/lifecycle/master.adoc
  archive/archived-titles/catalog/managing-products/aap-common
  archive/archived-titles/catalog/managing-products/catalog
  archive/archived-titles/catalog/managing-products/docinfo.xml
  archive/archived-titles/catalog/managing-products/master.adoc
  archive/archived-titles/catalog/receptor/.gitkeep
  archive/archived-titles/catalog/receptor/aap-common
  archive/archived-titles/catalog/receptor/assemblies
  archive/archived-titles/catalog/receptor/docinfo.xml
  archive/archived-titles/catalog/receptor/images
  archive/archived-titles/catalog/receptor/master.adoc
  archive/archived-titles/controller/aap-common
  archive/archived-titles/controller/attributes
  archive/archived-titles/controller/controller
  archive/archived-titles/controller/docinfo.xml
  archive/archived-titles/controller/master.adoc
  archive/archived-titles/hub/faq/aap-common
  archive/archived-titles/hub/faq/assemblies
  archive/archived-titles/hub/faq/attributes
  archive/archived-titles/hub/faq/docinfo.xml
  archive/archived-titles/hub/faq/master.adoc
  archive/archived-titles/hub/faq/modules
  archive/archived-titles/hub/obtaining-token/aap-common
  archive/archived-titles/hub/obtaining-token/attributes
  archive/archived-titles/hub/obtaining-token/automation-hub
  archive/archived-titles/hub/obtaining-token/docinfo.xml
  archive/archived-titles/hub/obtaining-token/hub
  archive/archived-titles/hub/obtaining-token/master.adoc
  archive/archived-titles/migration/aap-common
  archive/archived-titles/migration/attributes
  archive/archived-titles/migration/docinfo.xml
  archive/archived-titles/migration/master.adoc
  downstream/snippets/published-23.txt
Labels: Ready for peer review, 2.3

#841 Removed broken link from the installation guide
  downstream/modules/platform/proc-verify-controller-installation.adoc
Labels: 2.3, Needs backport to 2.3

#842 Removed broken link from the installation guide (#841)
  downstream/modules/platform/proc-verify-controller-installation.adoc
Labels: 2.3

#830 AAP-4208A updated accessibility formatting (#792)
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc
  downstream/modules/analytics/con-jobs-explorer.adoc
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/analytics/proc-create-savings-plan.adoc
  downstream/modules/analytics/proc-edit-savings-plan.adoc
  downstream/modules/analytics/proc-filter-plans.adoc
  downstream/modules/analytics/proc-link-plan-job-template.adoc
  downstream/modules/analytics/proc-view-failed-jobs-detail.adoc
  downstream/modules/automation-hub/proc-add-user-to-group.adoc
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
  downstream/modules/automation-hub/proc-create-groups.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-restore-aap-backup.adoc
Labels: 2.1, 2.2, Ready for peer review, 2.3

#831 AAP-4208A updated accessibility formatting (#792)
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc
  downstream/modules/analytics/con-jobs-explorer.adoc
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/analytics/proc-create-savings-plan.adoc
  downstream/modules/analytics/proc-edit-savings-plan.adoc
  downstream/modules/analytics/proc-filter-plans.adoc
  downstream/modules/analytics/proc-link-plan-job-template.adoc
  downstream/modules/analytics/proc-view-failed-jobs-detail.adoc
  downstream/modules/automation-hub/proc-add-user-to-group.adoc
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
  downstream/modules/automation-hub/proc-create-groups.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-restore-aap-backup.adoc
Labels: 2.1, 2.2, Ready for peer review, 2.3

#832 AAP-4208A updated accessibility formatting (#792)
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc
  downstream/modules/analytics/con-jobs-explorer.adoc
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/analytics/proc-create-savings-plan.adoc
  downstream/modules/analytics/proc-edit-savings-plan.adoc
  downstream/modules/analytics/proc-filter-plans.adoc
  downstream/modules/analytics/proc-link-plan-job-template.adoc
  downstream/modules/analytics/proc-view-failed-jobs-detail.adoc
  downstream/modules/automation-hub/proc-add-user-to-group.adoc
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
  downstream/modules/automation-hub/proc-create-groups.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-restore-aap-backup.adoc
Labels: 2.1, 2.2, Ready for peer review, 2.3

#840 Release notes: replace pulp_firewalld_zone with automationhub_firewalld_zone
  release-notes/topics/hub-460.adoc
Labels: Release notes, Technical review complete, 2.3, Needs backport to 2.3

#844 2.3 Release notes: replace pulp_firewalld_zone with automationhub_firewal…
  release-notes/topics/hub-460.adoc
Labels: 2.3

#845 Edits to Automation hub system requirements
  downstream/modules/platform/ref-automation-hub-requirements.adoc
Labels: 2.3, Needs backport to 2.3

#843 [2.3] AAP-4206: Add alt-text to images (#833)
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/con-navigator-modes.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-execute-playbook-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/security/con-automate-idps-rules.adoc
  downstream/modules/security/con-automating-firewall-rules.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
  downstream/modules/security/proc-deleting-firewall-rule.adoc
Labels: 2.1, 2.2, Ready for peer review, 2.3

#847 Edits to Automation hub system requirements (#845)
  downstream/modules/platform/ref-automation-hub-requirements.adoc
Labels: 2.3

#848 Edits to Automation hub system requirements for 2.2
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2

#801 Add Certified and Validated Content (AAP-5046a)
  downstream/assemblies/hub/assembly-faq.adoc
  downstream/assemblies/hub/assembly-private-automation-hub.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/automation-hub/con-remote-repos.adoc
  downstream/modules/automation-hub/con-required-shared-filesystem.adoc
  downstream/modules/automation-hub/con-rh-certified-synclist.adoc
  downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/automation-hub/proc-create-synclist.adoc
  downstream/modules/automation-hub/proc-enabling-firewall-services.adoc
  downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
  downstream/modules/automation-hub/proc-shared-filesystem.adoc
  downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3

#849 2.3 Add Certified and Validated Content (AAP-5046a) (#801)
  downstream/assemblies/hub/assembly-faq.adoc
  downstream/assemblies/hub/assembly-private-automation-hub.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/automation-hub/con-remote-repos.adoc
  downstream/modules/automation-hub/con-required-shared-filesystem.adoc
  downstream/modules/automation-hub/con-rh-certified-synclist.adoc
  downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/automation-hub/proc-create-synclist.adoc
  downstream/modules/automation-hub/proc-enabling-firewall-services.adoc
  downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
  downstream/modules/automation-hub/proc-shared-filesystem.adoc
  downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Labels: 2.3

#850 Document title changed
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
  downstream/titles/hub/install/master.adoc
Labels: Ready for technical review, Needs backport to 2.3, Title change

#851 Document title changed (#850)
  downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
  downstream/titles/hub/install/master.adoc
Labels: 2.3, Title change

#854 [Backport] - AAP-4206: Add alt-text to images (#833)
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/con-navigator-modes.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-execute-playbook-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/security/con-automate-idps-rules.adoc
  downstream/modules/security/con-automating-firewall-rules.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
  downstream/modules/security/proc-deleting-firewall-rule.adoc
Labels: 2.1, Ready for peer review

#853 [Backport] - AAP-4206: Add alt-text to images (#833)
  downstream/modules/analytics/proc-add-roles-to-group.adoc
  downstream/modules/analytics/proc-add-user-to-group.adoc
  downstream/modules/analytics/proc-create-groups.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/con-navigator-modes.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-execute-playbook-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/security/con-automate-idps-rules.adoc
  downstream/modules/security/con-automating-firewall-rules.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
  downstream/modules/security/proc-deleting-firewall-rule.adoc
Labels: 2.2, Ready for peer review

#839 Added default values of image.
  downstream/modules/builder/ref-build-args-base-image.adoc
Labels: 2.2, Needs backport to 2.2, Ready for technical review, 2.3, Needs backport to 2.3

#855 2.3 Added default values of image. (#839)
  downstream/modules/builder/ref-build-args-base-image.adoc
Labels: 2.3

#856 2.2 Added default values of image. (#839)
  downstream/modules/builder/ref-build-args-base-image.adoc
Labels: 2.2

#862 Removing instance of PostgreSQL statement
  downstream/modules/platform/ref-postgresql-requirements.adoc
Labels: 2.2, Needs backport to 2.2, 2.3, Needs backport to 2.3

#863 Removing instance of PostgreSQL statement (#862)
  downstream/modules/platform/ref-postgresql-requirements.adoc
Labels: 2.3

#864 Removing instance of PostgreSQL statement for 2.2
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2

#631 AAP-3677 Added information about which pods to expect
  downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
Labels: 2.1, 2.2, Needs backport to 2.1, Needs backport to 2.2, Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#866 CA-FIX - removed extra space to fix broken attribute
  downstream/assemblies/central-auth/assembly-central-auth-hub.adoc
Labels: 2.1, 2.2, Needs backport to 2.1, Needs backport to 2.2, Ready for peer review, 2.3, Needs backport to 2.3, 2.4

#861 Section added on enabling the hstore extension
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
Labels: Ready for peer review, Technical review complete, 2.4

#868 AAP-2080 added note about 301 redirect
  downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
Labels: Ready for peer review

#867 Removed automationcatalog inventory file variables
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-sso-variables.adoc
Labels: Technical review complete, 2.4

#852 AAP-8485 Document new variable "supervisor_start_retry_count" for AAP installer
  downstream/modules/platform/ref-controller-variables.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#878 Modifying master.adoc
  downstream/modules/automation-hub/proc-delete-user.adoc
  downstream/titles/hub/managing-user-access/master.adoc
Labels: 2.3

#879 Modifying master.adoc (#878)
  downstream/modules/automation-hub/proc-delete-user.adoc
  downstream/titles/hub/managing-user-access/master.adoc
Labels: 2.3

#882 Added nginx_tls_protocols to appendix
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.2, Needs backport to 2.2, Technical review complete, 2.3, Needs backport to 2.3, 2.4

#707 AAP-3275 added release notes for 2.1.2 and 2.1.3
  release-notes/master.adoc
  release-notes/master.html
  release-notes/topics/aap-211.adoc
  release-notes/topics/aap-212.adoc
  release-notes/topics/aap-213.adoc
Labels: 2.1, Ready for technical review

#883 Added nginx_hsts_max_age to appendix
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.3, Needs backport to 2.3, 2.4
