Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-03, with the labels that each got.

#884 Updating prerequisites for a synclist in hub
  downstream/modules/automation-hub/proc-create-synclist.adoc
Labels: Ready for peer review, Technical review complete, 2.3

#887 Updating prerequisites for a synclist in hub (#884)
  downstream/modules/automation-hub/proc-create-synclist.adoc
Labels: 2.3

#889 Updating prerequisites for a synclist in hub (#884) (#887)
  downstream/modules/automation-hub/proc-create-synclist.adoc
Labels: 2.2

#890 Updating prerequisites for a synclist in hub (#884) (#887) (#889)
  downstream/modules/automation-hub/proc-create-synclist.adoc
Labels: 2.1

#886 Updated automation hub ports table.
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.2, Needs backport to 2.2, Technical review complete, 2.3, Needs backport to 2.3, 2.4

#891 Updated automation hub ports table. (#886)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.3

#892 Updated automation hub and PostgreSQL ports tables
  downstream/modules/platform/ref-network-ports-protocols.adoc
Labels: 2.2

#897 AAP 9652: clarify websocket configuration in operations guide
  downstream/modules/platform/con-websocket-setup.adoc
Labels: Ready for peer review, Technical review complete, 2.3, 2.4

#899 Added nginx port variables to inventory appendix (#885)
  downstream/modules/platform/ref-controller-variables.adoc
Labels: 2.3

#901 Backport AAP 9652: clarify websocket configuration in operations guide (#897)
  downstream/modules/platform/con-websocket-setup.adoc
Labels: Ready for peer review, 2.3, Backported to 2.3

#900 AAP-9531 updated RHEL version notation
  downstream/assemblies/platform/assembly-upgrading-controller.adoc
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
Labels: 2.1, 2.2, Ready for peer review, Technical review complete, 2.3

#905 AAP-9531 updated RHEL version notation (#900)
  downstream/assemblies/platform/assembly-upgrading-controller.adoc
Labels: 2.1, Ready for peer review

#904 2.2 AAP-9531 updated RHEL version notation (#900)
  downstream/assemblies/platform/assembly-upgrading-controller.adoc
Labels: 2.2, Ready for peer review

#903 2.3 AAP-9531 updated RHEL version notation (#900)
  downstream/assemblies/platform/assembly-upgrading-controller.adoc
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
Labels: Ready for peer review, 2.3

#898 Created templates for future release notes
  downstream/snippets/aap-rn-template.adoc
  downstream/snippets/assembly-rn-template.adoc
  downstream/snippets/controller-rn-template.adoc
  downstream/snippets/hub-rn-template.adoc
  downstream/snippets/operator-rn-template.adoc
  release-notes/master.adoc
Labels: Release notes, Ready for peer review

#906 Addition of catalog.redhat.com
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: Ready for peer review, Ready for technical review, Technical review complete, 2.3, Needs backport to 2.3

#907 Addition of catalog.redhat.com (#906)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.3

#902 AAP-4208-2.3 updated accessibility formatting (further fixes) (#888)
  downstream/assemblies/catalog/assembly-installing-receptor.adoc
  downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc
  downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc
  downstream/modules/automation-hub/proc-add-container-readme.adoc
  downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc
  downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/automation-hub/proc-create-credential.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/automation-hub/proc-downloading-signature-public-keys.adoc
  downstream/modules/automation-hub/proc-edit-namespace.adoc
  downstream/modules/automation-hub/proc-push-container.adoc
  downstream/modules/automation-hub/proc-review-collection-imports.adoc
  downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-pull-protected-registry.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-creating-controller-form-view.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-importing-collections-into-private-automation-hub.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
  downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
Labels: Ready for peer review

#908 2.2 AAP-4208 updated accessibility formatting (further fixes) (#888)
  downstream/assemblies/catalog/assembly-installing-receptor.adoc
  downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc
  downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc
  downstream/modules/automation-hub/proc-add-container-readme.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-edit-namespace.adoc
  downstream/modules/automation-hub/proc-push-container.adoc
  downstream/modules/automation-hub/proc-review-collection-imports.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-pull-protected-registry.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-creating-controller-form-view.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
Labels: 2.2, Ready for peer review

#911 Added automationhub variable (#880)
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.3

#910 2.1 AAP-4208 updated accessibility formatting (further fixes) (#888)
  downstream/assemblies/catalog/assembly-installing-receptor.adoc
  downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc
  downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc
  downstream/modules/automation-hub/proc-add-container-readme.adoc
  downstream/modules/automation-hub/proc-delete-collection.adoc
  downstream/modules/automation-hub/proc-edit-namespace.adoc
  downstream/modules/automation-hub/proc-push-container.adoc
  downstream/modules/automation-hub/proc-review-collection-imports.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-pull-protected-registry.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-controller-route-options.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
Labels: 2.1, Ready for peer review

#912 Correcting minor errors
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/automation-hub/proc-add-container-readme.adoc
  downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc
  downstream/modules/automation-hub/proc-add-user-to-group.adoc
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
  downstream/modules/automation-hub/proc-delete-container.adoc
  downstream/modules/automation-hub/proc-pull-image.adoc
  downstream/modules/automation-hub/proc-tag-image.adoc
  downstream/modules/automation-hub/ref-container-permissions.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3, 2.4

#893 Added information about pulling container images
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3, 2.4

#917 Added information about pulling container images (#893)
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.3

#922 Updated document
  downstream/assemblies/hub/assembly-container-user-access.adoc
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc
  downstream/modules/automation-hub/proc-add-user-to-group.adoc
  downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc
  downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
  downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/automation-hub/proc-create-groups.adoc
  downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/automation-hub/proc-obtain-images.adoc
  downstream/modules/automation-hub/proc-pull-image.adoc
  downstream/modules/automation-hub/proc-push-container.adoc
  downstream/modules/automation-hub/proc-tag-image.adoc
  downstream/modules/automation-hub/proc-tag-pulled-image.adoc
  downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc
  downstream/modules/automation-hub/ref-container-permissions.adoc
Labels: 2.2, Ready for peer review, 2.3, 2.4

#923 2.3 Updated document (#922)
  downstream/assemblies/hub/assembly-container-user-access.adoc
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc
  downstream/modules/automation-hub/proc-add-user-to-group.adoc
  downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc
  downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/automation-hub/proc-assigning-permissions.adoc
  downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/automation-hub/proc-create-groups.adoc
  downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/automation-hub/proc-obtain-images.adoc
  downstream/modules/automation-hub/proc-pull-image.adoc
  downstream/modules/automation-hub/proc-push-container.adoc
  downstream/modules/automation-hub/proc-tag-image.adoc
  downstream/modules/automation-hub/proc-tag-pulled-image.adoc
  downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc
  downstream/modules/automation-hub/ref-container-permissions.adoc
Labels: 2.3

#924 Added admonition for Catalog docs
  downstream/aap-common/sunset-catalog-content-admonition.adoc
  downstream/titles/catalog/getting-started/master.adoc
  downstream/titles/catalog/itsm-integration/master.adoc
  downstream/titles/catalog/onboarding/master.adoc
  downstream/titles/catalog/support-matrix/master.adoc
  downstream/titles/worker-install/master.adoc
Labels: Needs backport to 2.2, Ready for peer review, 2.3

#925 Added admonition for Catalog docs (#924)
  downstream/aap-common/sunset-catalog-content-admonition.adoc
  downstream/titles/catalog/getting-started/master.adoc
  downstream/titles/catalog/itsm-integration/master.adoc
  downstream/titles/catalog/onboarding/master.adoc
  downstream/titles/catalog/support-matrix/master.adoc
  downstream/titles/worker-install/master.adoc
Labels: 2.2

#928 Moved 'routable_hostname' variable
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: Ready for technical review, 2.3, Needs backport to 2.3, 2.4

#929 2.3 Moved 'routable_hostname' variable (#928)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.3

#932 AAP-9671 updated Introduction
  downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Labels: Ready for peer review, Technical review complete, 2.3

#936 Add attribute for RH-SSO
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.2, Ready for peer review, attributes, Needs backport to 2.3

#939 AAP-9671 updated Introduction (#932)
  downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
Labels: Ready for peer review, 2.3
