Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-07, with the labels that each got.

#1177 Backport pull request #1061 from main to 2.4
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: Ready for peer review, 2.4

#1178 Backport pull request #1061 from main to 2.3
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: Ready for peer review, 2.3

#1179 Replace acme.org with example.com
  downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
  downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
  downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
  downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: Ready for peer review, Technical review complete, 2.4, Needs backport to 2.4

#1182 Corrected install instructions
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: Ready for peer review, Technical review complete, 2.4, Needs backport to 2.4

#1183 Corrected install instructions (#1182)
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: 2.4

#1184 Corrected ansible version
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for technical review, 2.4, Needs backport to 2.4

#1185 Corrected ansible version (#1184)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.4

#1186 Corrected ansible version for 2.3
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.3

#1187 Corrected Ansible version for 2.2
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2

#1103 AAP-12941 updated link title
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Ready for technical review, 2.3

#1110 AAP-12941A updated wording within link title
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: 2.4

#1191 AAP-12941A updated wording within link title (#1110)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Ready for peer review, 2.4

#1194 Created Attribute
  downstream/attributes/attributes.adoc
Labels: 2.4, Needs backport to 2.4

#1196 Create attribute
  downstream/attributes/attributes.adoc
Labels: 2.3

#1169 Building a custom decision environment steps
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
  downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
  downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
Labels: Ready for technical review, 2.4, Needs backport to 2.4

#1180 Updated vague wording
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
Labels: Ready for peer review, 2.4, Needs backport to 2.4

#1205 2.4 Updated vague wording (#1180)
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
Labels: 2.4

#1218 AAP-483: Corrected the podman login registry address
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
Labels: Ready for peer review

#1197 AAP-13831 Clarifies user privilege requirements in Planning Guide
  downstream/assemblies/platform/assembly-system-requirements.adoc
Labels: Ready for peer review, 2.3, 2.4

#1223 2.2 Backport PR #1217 to AAP v2.2
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: 2.2, Ready for peer review

#1203 Remove empty Additional Resources sections
  downstream/archive/archived-assemblies/aap-on-azure/assembly-aap-azure-install.adoc
  downstream/archive/archived-modules/platform/proc-configuring-proxy-support-controller.adoc
  downstream/assemblies/builder/assembly-intro-to-builder.adoc
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/security/con-about-firewall-policy-management.adoc
  downstream/modules/security/con-automate-idps-rules.adoc
  downstream/modules/security/proc-creating-idps-rule.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#1224 Added automationedacontoller_pg_* variables
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.4, Needs backport to 2.4

#1229 Added automationedacontoller_pg_* variables (#1224)
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.4

#1230 Backport PR #1218 to AAP v2.1
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
Labels: 2.1, Ready for peer review

#1231 Backport PR #1218 to AAP v2.2
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
Labels: 2.2, Ready for peer review

#1232 Backport PR #1218 to AAP v2.2
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
Labels: Ready for peer review, 2.3

#1233 Backport PR #1218 to AAP v2.4
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
Labels: Ready for peer review, 2.4

#1216 AAP-2133: Added specifications for AAP database node
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.1, Ready for peer review

#1242 Backport pull request #1216 from main to 2.2
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2, Ready for peer review

#1243 AAP-537-v23: Corrected the Ansible Builder and Python38 version number
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: 2.3

#1219 AAP-14132 updated Chapter 8. Migrating RH AAP to AAP Operator
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: Ready for peer review, Technical review complete, 2.4

#1245 AAP-14132 updated Chapter 8. Migrating RH AAP to AAP Operator (#1219)
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: Ready for peer review, 2.4

#1246 AAP-14132 updated Chapter 8. Migrating RH AAP to AAP Operator (#1219)
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: Ready for peer review, 2.3

#1247 AAP-14132 updated Chapter 8. Migrating RH AAP to AAP Operator (#1219)
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: 2.2, Ready for peer review

#1244 AAP-14410: Restructured the AAP 1.2 release notes
  release-notes/master.adoc
  release-notes/topics/aap-126.adoc
  release-notes/topics/hub-421.adoc
  release-notes/topics/hub-422.adoc
  release-notes/topics/hub-423.adoc
  release-notes/topics/hub-424.adoc
  release-notes/topics/hub-426.adoc
  release-notes/topics/insights-062021.adoc
  release-notes/topics/insights-102021.adoc
  release-notes/topics/platform-intro.adoc
  release-notes/topics/tower-intro-381.adoc
  release-notes/topics/tower-intro-382.adoc
  release-notes/topics/tower-intro-383.adoc
  release-notes/topics/tower-intro-384.adoc
Labels: Ready for peer review

#1213 AAP-14004: Restructured the AAP 2.2 release notes
  release-notes/master.adoc
  release-notes/topics/aap-22.adoc
  release-notes/topics/aap-221.adoc
  release-notes/topics/controller-420.adoc
  release-notes/topics/hub-450.adoc
  release-notes/topics/operator-220.adoc
  release-notes/topics/platform-intro.adoc
Labels: 2.2, Ready for peer review

#1212 AAP-14003: Restructured the AAP 2.3 release notes
  release-notes/master.adoc
  release-notes/topics/aap-23.adoc
  release-notes/topics/controller-430.adoc
  release-notes/topics/docs-23.adoc
  release-notes/topics/hub-460.adoc
  release-notes/topics/operator-230.adoc
  release-notes/topics/platform-intro.adoc
Labels: Ready for peer review, 2.3

#1250 AAP-960: Updated the minimum requirements for execution nodes
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: Ready for peer review

#1251 AAP-960-v22: Updated the minimum requirements for execution nodes
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2, Ready for peer review

#1255 AAP-3051: Updated Automation Analytics docs product name in the abstract
  downstream/titles/analytics/reports/docinfo.xml
Labels: Ready for peer review

#1253 Backport pull request #1250 from main to AAP v2.4
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: Ready for peer review, 2.4

#1254 Backport pull request #1250 from main to AAP v2.3
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: Ready for peer review, 2.3

#1214 AAP-14005: Restructured the AAP 2.1 release notes
  release-notes/master.adoc
  release-notes/topics/aap-21.adoc
  release-notes/topics/aap-211.adoc
  release-notes/topics/aap-212.adoc
  release-notes/topics/aap-213.adoc
  release-notes/topics/aap-214.adoc
  release-notes/topics/controller-41.adoc
  release-notes/topics/controller-411.adoc
  release-notes/topics/controller-414.adoc
  release-notes/topics/hub-441.adoc
  release-notes/topics/hub-443.adoc
  release-notes/topics/platform-intro.adoc
Labels: 2.1, Ready for peer review

#1257 Replace the word 'leverage'
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/modules/eda/con-about-event-driven-ansible.adoc
  downstream/modules/platform/con-about-eda-controller.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: 2.4, Needs backport to 2.4

#1258 Replace the word 'leverage' (#1257)
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/modules/eda/con-about-event-driven-ansible.adoc
  downstream/modules/platform/con-about-eda-controller.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: 2.4

#1235 Updating EDA controller user guide asciidoc
  downstream/assemblies/eda/assembly-eda-decision-environments.adoc
  downstream/assemblies/eda/assembly-eda-projects.adoc
  downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
  downstream/assemblies/eda/assembly-eda-set-up-token.adoc
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
  downstream/modules/eda/proc-eda-activate-webhook.adoc
  downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
  downstream/modules/eda/proc-eda-set-up-new-project.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
  downstream/modules/eda/proc-eda-set-up-token.adoc
  downstream/modules/eda/proc-eda-test-with-K8s.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: 2.4

#1192 AAP-13734 Updates to code samples for sections 2.1.1.4 - 2.1.1.6 in the Installation Guide
  downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
  downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
Labels: Ready for peer review, Needs backport to 2.4

#1266 Added edit icon
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
Labels: 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#1267 Added edit icon (#1266)
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
Labels: 2.4

#1269 Replace icon (#1268)
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
Labels: 2.4

#1270 Replaced attribute with Unicode icon
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
Labels: 2.3, Needs backport to 2.3, 2.4, Needs backport to 2.4

#1271 Replaced attribute with Unicode icon (#1270)
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
Labels: 2.4

#1272 Replace settings icon with unicode image
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
Labels: 2.3
