Repository RedHatInsights/red-hat-ansible-automation-platform-documentation, pull requests merged in 2023-01, with the labels that each got.

#720 AAP-3803 updated FAQ section of Ansible Navigator Guide 2.1
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.1, Ready for peer review

#703 AAP-4995 - Add AWX deployment to list of migration options
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review, 2.3, Needs backport to 2.3

#693 AAP-3514 added links for OCP install of AAP
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review, 2.3, Needs backport to 2.3

#721 AAP-4995 - Add AWX deployment to list of migration options (#703)
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: Backported to 2.3

#726 Corrected Platform version
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Labels: Needs backport to 2.3

#730 Changed text format
  downstream/modules/automation-hub/con-ha-hub-installation.adoc
Labels: Needs backport to 2.3

#732 Corrected typo
  downstream/assemblies/hub/assembly-installing-high-availability-hub.adoc
Labels: Needs backport to 2.2, Needs backport to 2.3

#719 AAP-6697 updated builder guide section 2.1
  downstream/modules/builder/proc-installing-builder.adoc
Labels: 2.2, Ready for technical review

#741 AAP-PG - Fixed typo in Ansible version
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.3, Needs backport to 2.3

#743 AAP-4205 Adds alt text to xrefs
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review, 2.3, Needs backport to 2.3

#745 AAP-8064 Updated code in step 3 of chpt 5.2, per SME
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: Ready for peer review, Ready for technical review

#735 AAP-8221 - Refining Planning Guide structure
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-attaching-subscriptions.adoc
  downstream/assemblies/platform/assembly-choosing-obtaining-installer.adoc
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/con-about-automation-controller.adoc
  downstream/modules/platform/con-about-automation-hub.adoc
  downstream/modules/platform/con-about-execution-env.adoc
  downstream/modules/platform/con-about-galaxy.adoc
  downstream/modules/platform/con-about-navigator.adoc
  downstream/modules/platform/con-about-pa-hub.adoc
  downstream/modules/platform/con-about-services-catalog.adoc
  downstream/modules/platform/con-overview-automation-mesh.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-platform-components.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3

#717 AAP-7870 updated installation guide
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Labels: Ready for peer review, 2.3

#747 AAP-7625 - added information for RPM installed package
  downstream/modules/platform/proc-editing-inventory-file.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3, Docathon

#710 AAP4482 - add missing steps for configuring a Container Registry
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/automation-hub/proc-create-credential.adoc
  downstream/modules/automation-hub/proc-pull-image.adoc
  downstream/modules/builder/proc-pull-protected-registry.adoc
Labels: Not ready for peer review, Ready for technical review, 2.3, Needs backport to 2.3

#758 AAP-8273 Updated postgresql version from 12 to 13.
  downstream/modules/platform/proc-verify-network-connectivity.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3

#738 AAP-7610 Added troubleshooting topic and included procedure
  downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
  downstream/titles/aap-operator-backup/master.adoc
Labels: 2.2, Needs backport to 2.2, Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#757 AAP-8071 Wrong database guidelines have been updated in planning guide
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for peer review, 2.3, Needs backport to 2.3

#764 AAP-7870 updated installation guide (#717)
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Labels: Ready for peer review, 2.3

#771 AAP-7897 Fix link in installation guide overview chapter
  downstream/modules/platform/con-aap-installation-prereqs.adoc
Labels: Needs backport to 2.3

#772 AAP-7870A fixed git merge conflict in 2.3
  downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Labels: Ready for peer review, 2.3

#773 Re-added modules to inventory file chapter
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
Labels: Needs backport to 2.3

#751 AAP-592 updated FAQ section
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.1, 2.2, 2.3

#777 AAP-592 updated Navigator FAQ section (#751)
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.3

#740 Added installation note for private hub
  downstream/modules/platform/ref-automation-hub-requirements.adoc
Labels: Needs backport to 2.3

#776 AAP-592 updated Navigator FAQ section (#751)
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.2

#718 Removed Organization Administrator role
  downstream/titles/catalog/getting-started/master.adoc
Labels: Ready for peer review, Technical review complete, 2.3

#763 AAP-7888 - Added details about sticky sessions
  downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
  downstream/assemblies/platform/snippets
  downstream/modules/platform/con-sticky-sessions.adoc
Labels: Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#725 AAP-7858 - added information re tech preview features
  release-notes/master.html
  release-notes/topics/aap-23.adoc
  release-notes/topics/platform-intro.adoc
Labels: Release notes, Ready for peer review, Technical review complete, 2.3, Needs backport to 2.3

#791 Corrections to OCP Performance doc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
Labels: Technical review complete, Needs backport to 2.3
